# python tests/decode.py

import bz2
import base64

# The compressed and encoded string (example value, replace with actual compressed_string)
compressed_string = "QlpoOTFBWSZTWRXCe/AAEg7aAH/WyAN+IABAYAe/eAAAAAzgKsAA7Bgk0iabUmQeUGp+iI1EQIehCgAGgZMgSeqUqaDQAAKAAaBkyBElJowJpgJvp+BCLFQJER5oQLIOtUnCqbz1/fP379enBCUUaKhJpBoMZCk1GNGQ2gqigtGLCUmiiSi0YgCNFGxGjFFFkNMNRJYlIswk2TRohAxRjBRixRggiiggo2KQtBkALMKAqYsNBjGgGJo1lLFEGjUlUbRRRJrRYoMBRjERGojQURY1JCVG0bEURaiKNGkxqKNJgxCEBRiIIowaxjJFsRojUYTYpMxMzYtIlmbFCWorGpIgqTFojYmaDQUGxsUFEzDIyYzMGNUZMWIigig0YsMIwZNsWMmksaIIxWNGAjaRNjGsRSYjYyFEWKk0Qy2NGxFBkEsRFRM0RFRg2DYIigxaxFQQmgLGjWKkTYIKSiZTCKDed1iEiKCKKEoNioEtGaVBEQmZEQzTCktFQy0SaEylRGLBsVEUYJEtAwTQElEWEZJBFBrJFKbGJMFBiNMkCCQl/DfrO4I73HGqhUDKptU/kaA1TGPbeHMv7VwEMUwQxaNWx+DAk+Ibx4yw0EzS/3E/XOVl6y09ZHBKzRNyVIpQU6KhqyEbp2nGFtBdsSp+jsxsvAIaBAhKo9LyuXLbDBOmtfcaQKhJ+/jvLx7nB00SQ0t2ouq3GIXlpPGw1XhvpOqQpy5RQXkZYwQvdpqb7rUK57SqW8VuWDdb6ukAAsK62pfkZHvPCtYVejw+FRsWNTtlJiBcEypFADUEn1yVVNqncrEzQunfUnrbwKFK2XzPWMLliwkfNMDMZ4dxQTMHQp1y4dlmxZbMa5lecW3e9VhsELTmpEcsbR6uZC8LEW3l4WEOySQCQbRGixVRaNUWijBtisbY2io0W2i2KxYtGLRWEtRsWxRY22No20VijJtotk1FGrGxa1JVby2rXkJSZo+LdMZErpyTTJd1w9e6CR53EzruUHJ10m7uIkd3jeCgkXndmjlxy43J3RimSmJOckkiJLatJuu3aBBFuRxJoSmc4MMhXdcnO7u0TzuMud47lx3drVpVxmjbxt0xqK0aA2NG2ndtXIjWooItCVua3hJFKCyizJTLKSiJVFEIBLe/fc/qCCMgKCkipdlMdDY635hY4dKlSAX0xIfal6EgFosIAqT1KBpAMot1/i7kinChICuE9+A="

# Step 1: Base64 decode the compressed string
compressed_data = base64.b64decode(compressed_string.encode("utf-8"))

# Step 2: Decompress the data using BZ2
decompressor = bz2.BZ2Decompressor()
decompressed_data = decompressor.decompress(compressed_data)

# Convert bytes back to the original string
original_string = decompressed_data.decode("utf-8")

with open("tests/8.txt", "w") as f:
    f.write(original_string)
